### ISSUE TITLE
Dエンジェル・オリヴィエの場合コピペしてそのまま参加できない

### ISSUE THREAD

**Issue by ika3** [59naga/gbf-raid-stream#4]
> ******** Dエンジェル・オリヴィエHL 数秒前

******** DまでIDとして認識してしまうので

**Comment by 59naga** [comment]
ご報告ありがとうございます。遅くなりましたが、`v0.0.14`として対応させていただきました。

IDとして認識されそうなボス名のときだけ（現在はオリヴィエのみですが）IDだけコピーするように修正しています

・ポップアップ表示→従来どおり（******** Dエンジェル・オリヴィエHL 数秒前）
・クリップボード→`********`

<img width="480" alt="2019-01-03 10 26 47" src="https://user-images.githubusercontent.com/1548478/50620335-1c62b580-0f42-11e9-8e6e-9cbb95ec94ea.png">
